@TaskManagementSystem.API_HostAddress = http://localhost:5049
@token = {{login.response.body.token}}

### Register a new user
# @name register
POST {{TaskManagementSystem.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "Password123!",
  "role": 0
}

###

### Login
# @name login
POST {{TaskManagementSystem.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "Password123!"
}

###

### Get current user profile (requires JWT)
GET {{TaskManagementSystem.API_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}

###
